Post feed and create post page integrated
hackslash-nitp/cura pull request #90
Opened 2022-12-26 15:25 UTC by shazebK

I have done some style related changes in postfeed.dart and created the functionality to create a post by the user which later can be visible on the postfeed page.

Please review this PR and merge 😊.

![postfeed](https://user-images.githubusercontent.com/106864146/209563437-9c22ece7-30a3-405b-bfa5-659e06759b19.jpeg)

2022-12-31 13:42 UTC, RitwikSingh28 commented on lib/main.dart
> -      initialRoute: auth.getCurrentUser() == null
@shazebK can you reset the initialRoute to its initial config please? Thanks! :+1:

2022-12-31 13:44 UTC, RitwikSingh28 requested changes
Splendidly done! :sparkler: 

Please just make one change, and after that we would be good to go

2022-12-31 13:51 UTC, shazebK commented
Ok I will try

2023-01-01 06:24 UTC, shazebK commented
@RitwikSingh28 
I have made the necessary changes as requested

2023-10-04 06:27 UTC, RitwikSingh28 approved these changes
No issues now... Merging!

2023-10-04 06:27 UTC, merged